name: Deploy

on:
  push:
    branches:
      - 'master'

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup JDK
      uses: actions/setup-java@v3
      with:
        java-version: 11
        distribution: adopt
        server-id: ossrh
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD
        gpg-private-key: ${{ secrets.PGP_KEY }}
        gpg-passphrase: PGP_PASSPHRASE
    - name: Build and Deploy with Maven
      run: mvn -B -P sign-artifacts clean deploy --no-transfer-progres
      env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
